# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b446ea23f62c0dbd85f8ed58125713d5c08c84cb191a7df14716cb379448fd1976b514d93dbd839fd23d6ac56f4da33a9629ff6df263a735109b5eda8e627a8

test:
  secret_key_base: ee4f198d5b9a624f7be574b849980c1af170f9ab718d39c00b77f2ca1b7886c5f82f90a3c5eab285676e2eaf9ec73618be222509ab87f1ed251a46defce85254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
